chore(azure-pipelines.yml): add conditional check for number of issues found in the code analysis results to fail the pipeline if more than one issue is found
The code in the azure-pipelines.yml file has been modified to include a conditional check for the number of issues found in the code analysis results. If the number of issues is greater than one, the pipeline will fail and display a message indicating the number of issues found. If no issues are found, the pipeline will continue. This change improves the pipeline's ability to detect and handle code issues during the build process.

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -53,3 +53,9 @@ stages:
                   jq --arg BREAK "$BREAK" '.severity_counters[$BREAK] // 0' $resultsFilePath
                   noIssues=$(jq --arg BREAK "$BREAK" '.severity_counters[$BREAK] // 0' $resultsFilePath)
                   echo "Number of issues: $noIssues"
+                  if [ "$noIssues" -gt 1 ]; then
+                    echo "Pipeline failed due to more than $issueSeverity issue(s) found."
+                    exit 1
+                  else
+                    echo "No issue found. Pipeline continues."
+                  fi
