fix(azure-pipelines.yml): update script to check for more than 1 'warning' level issue in SARIF file and fail pipeline if found
The script in the azure-pipelines.yml file has been updated to check for more than 1 'warning' level issue in the SARIF file. If more than 1 issue is found, the pipeline will fail. This change improves the pipeline's quality control by ensuring that only a limited number of 'warning' level issues are allowed.

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -46,5 +46,17 @@ stages:
                 targetType: 'inline'
                 script: |
                   sarifFilePath="$(Pipeline.Workspace)/results.sarif"
-                  jq -V
-                  jq '.severity_counters.MEDIUM' $sarifFilePath
+                  mediumSeverityRules=$(jq '[.runs[].tool.driver.rules[] | select(.defaultConfiguration.level == "warning")] | length' $sarifFilePath)
+                  # Check if jq returned a valid number and fail if not
+                  if ! [[ $mediumSeverityRules =~ ^[0-9]+$ ]]; then
+                      echo "Error: Failed to parse the count of 'warning' level issues from the SARIF file."
+                      exit 1
+                  fi
+
+                  # Checking if there are more than 1 'warning' (MEDIUM) severity rules
+                  if [ "$mediumSeverityRules" -gt 1 ]; then
+                      echo "Pipeline failed due to more than 1 'warning' level issue found."
+                      exit 1
+                  else
+                      echo "No more than 1 'warning' level issue found. Pipeline continues."
+                  fi
