chore(azure-pipelines.yml): update pipeline steps for security scan artifact handling and medium issue check
The pipeline steps for handling the security scan artifact result have been updated. Instead of using a Bash script to query the scan artifact result, the artifact is now downloaded using the "DownloadPipelineArtifact" task.

A new task "Check for MEDIUM issues in the scan result" has been added. This task uses a Bash script to check for MEDIUM issues in the scan result. It retrieves the path to the sarif file and uses jq to extract the number of MEDIUM issues. If there are more than 1 MEDIUM issue, the pipeline fails. Otherwise, the pipeline continues.

These changes improve the readability and maintainability of the pipeline and provide better handling of the security scan artifact result.

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -24,34 +24,28 @@ stages:
             inputs:
               pathToPublish: $(System.DefaultWorkingDirectory)/results.sarif
               artifactName: CodeAnalysisLogs
-          - task: Bash@3
-            displayName: 'Query the Scan Artifact Result - KICS Scanning'
+          - task: DownloadPipelineArtifact@2
+            displayName: 'Download the Security Scan Artifact Result - KICS Scanning'
             inputs:
-              targetType: 'inline' # 'filePath' | 'inline'. Type. Default: filePath.
-              script: |
-                ls -l results.sarif
-                echo "Let me try to find out if any error here >>>"
-                cat results.sarif | grep error
-                if [ $? -eq 0 ]
-                then
-                  echo "Failure: I found error <<severity: 'MEDIUM'>> in result, then failed."
-                  exit 1
-                else
-                  echo "Success: I did not find any error <<severity: 'MEDIUM'>> in result, then successed."
-                  exit 0
-                fi
-              failOnStderr: true # boolean. Fail on Standard Error. Default: false.
+              artifact: CodeAnalysisLogs
 
-              
-              
-
-
-
-          # # Download the scan result, artifiact
-          # - task: DownloadPipelineArtifact@2
-          #   displayName: 'Download the Security Scan Artifact Result - KICS Scanning'
-          #   inputs:
-          #     artifact: CodeAnalysisLogs
+          - task: Bash@3
+            displayName: "Check for MEDIUM issues in the scan result"
+            inputs:
+                failOnStderr: true
+                targetType: 'inline'
+                script: |
+                  sarifFilePath="$(Pipeline.Workspace)/results.sarif"
+                  echo "sarifFilePath: $sarifFilePath"
+                  mediumIssues=$(jq '.severity_counters.MEDIUM' $sarifFilePath)
+            
+                  if [ "$mediumIssues" -gt 1 ]; then
+                      echo "Pipeline failed due to $mediumIssues MEDIUM issue found."
+                      exit 1
+                  else
+                      echo "No issue found. Pipeline continues."
+                  fi
+          
 
           # # Bash v3
           # # Run a Bash script to parsing the result on macOS, Linux, or Windows.
